import React from 'react';
import type { NextPage } from "next";
import { unstable_getServerSession } from "next-auth";
import Head from "next/head";
import { authOptions } from "../../api/auth/[...nextauth]";
import { LayoutAdmin } from '../../../components/layout';
import { useRouter } from 'next/router';
import { items } from './menuItens';
import CardPlatform from '../../../components/platform/card';
import { Col, Row } from 'antd';
import axios from 'axios';
import { useSession } from 'next-auth/react';
import { useFetch } from '../../../hooks/useFetch';

type Props = {
    platforms: any;
};

const Home: NextPage<Props> = (props) => {
    const session = useSession()
    const options = {
        method: 'get',
        headers: {
            "Authorization": `Bearer ${session?.data?.token.accessToken}`
        }
    }
    const fetcher = (...args:any) => {
        const res = axios.get(args);
        return res;
    }
    const { data, error } = useFetch("/api/platforms", options);
    const platforms = props.platforms;
    const router = useRouter()
    return <>
        <Head>
            <title>Plataformas</title>
            <meta
                name="description"
                content="Generated by create next app"
            />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <LayoutAdmin menuItems={items}>
        <Row gutter={[16, 16]}>
        </Row>
        <Row gutter={[16, 16]}>
            {data && data.map((platform: any) => {
                return <Col span={6}>
                    <CardPlatform platform={platform} />
                </Col>
            })}
        </Row>
        </LayoutAdmin>
    </>
};

export async function getServerSideProps(context: { req: any; res: any; }) {
    const { req, res } = context;
    const session = await unstable_getServerSession(req, res, authOptions);
    if (!session) {
        return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }
    return {
        props: {
        },
    }
}

export default Home;
