import { getToken } from "next-auth/jwt"
import { Avatar} from 'antd';
import React from 'react';
import type { NextPage } from "next";
import { unstable_getServerSession } from "next-auth";
import Head from "next/head";
import { authOptions } from "../api/auth/[...nextauth]";
import { LayoutAdmin } from '../../components/layout';
import { Card } from 'antd';
import { EditOutlined, EllipsisOutlined, SettingOutlined } from '@ant-design/icons';
import Meta from 'antd/lib/card/Meta';
import { useSession } from 'next-auth/react';

//importar sessão do usuário


//card component antd
const CardSorteio = () => {
    return (
        <Card
    style={{ width: 300 }}
    actions={[
        <SettingOutlined key="setting" />,
        <EditOutlined key="edit" />,
        <EllipsisOutlined key="ellipsis" />,
    ]}
>
    <Meta
        avatar={<Avatar src="https://joeschmoe.io/api/v1/random" />}
        title="Card title"
        description="This is the description"
    />
</Card>
    );
}



const Home: NextPage = (props) => {
    const { data: session, status } = useSession();
    return <>
            <Head>
                <title>Auth</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        <LayoutAdmin>
            <CardSorteio />
        </LayoutAdmin>
        </>
};

export async function getServerSideProps(context: { req: any; res: any; }) {
    const { req, res } = context;
    const session = await unstable_getServerSession(req, res, authOptions);

    if (!session) {
            return {
            redirect: {
                destination: '/',
                permanent: false,
            },
        }
    }
    //serialize session

        return {
            props: {
            session: JSON.stringify(session),
            },
        }
}

export default Home;
